### ISSUE TITLE
Pivot :: choose a subset of value to pivot

### ISSUE THREAD

**Issue by rhuille** [ToucanToco/toucan-data-sdk#24]
Merger un domaine sur lui-même, pour avoir par exemple 2 colonnes de valeurs sur lesquelles faire un calcul

**Comment by PrettyWood** [comment]
Not sure it's the best way of solving the described issue! Could you please provide a scenario ?

**Comment by rhuille** [comment]
I agree with you: the need is poorly defined. I talked with some datastorytellers and the use case is the following : 

I want to transform this dataset: 
<img width="209" alt="Untitled" src="https://user-images.githubusercontent.com/15191323/63159452-e3cca380-c01b-11e9-8882-09f68f92a85f.png">

into:
<img width="219" alt="Untitled" src="https://user-images.githubusercontent.com/15191323/63159472-edeea200-c01b-11e9-9d2d-8f9ee28ac0cb.png">

We want to pivot the `REF` value from the column `type`, but not `A` and `B`

NB : 
- This transformation is almost achieved by the `pivot_by_group`... but it is not :(
- Currently, this transformation is achieved by  `compute_freq_by_critreria`. This an ugly trick, because this latter is not made for this use.
- See an exemple in this screen: https://coty.toucantoco.com/market-insight?report=GLOBAL&slide=105005&stage=staging
