### ISSUE TITLE
add a `filter_by_date` postprocess

### ISSUE THREAD

**Issue by adimascio** [ToucanToco/toucan-data-sdk#97]
## Need

Filter a dataframe according to certain date specifications, e.g. :

1. where *date* equals '2018-01-02'`
2. where *date* is between 2018-01-02 and 2018-01-05
3. where *date* is between 2018-01-02 and 50 days afterwards
4. where *date* is TODAY
5. where *date* is between TODAY and TODAY+30 days

## Implementation

Here is a possible python signature, followed by calls corresponding to use cases described above:

```python
def filter_by_date(df, date_col, date_fmt='%Y-%m-%d', start=None, stop=None, delta=None):
    pass
```

- case 1 : `filter_by_date(df, 'date', start='2018-01-02')`
- case 2 : `filter_by_date(df, 'date', start='2018-01-02', stop='2018-01-05')`
- case 3 : `filter_by_date(df, 'date', start='2018-01-02', delta='50days')`
- case 4 : `filter_by_date(df, 'date', start='TODAY')`
- case 5 : `filter_by_date(df, 'date', start='TODAY', delta='30days')`

`detla` would accept any timedelta syntax supported by pandas (cf. http://pandas.pydata.org/pandas-docs/stable/timedeltas.html).

Callers should either specify `start`, `stop`, `start` and `stop`, `start` and `delta` or `stop` and `delta`.

Symbolic names such as `TODAY`, `YESTERDAY` and `TOMORROW` should be supported.

**Comment by piotch** [comment]
I was also thinking of a convention whereby : 

* if `start` and `delta` are specified, the delta is **added** to `start` date
* if `end` and `delta` are specified, the delta is **substracted** to `end` date

**Comment by adimascio** [comment]
I created [This PR}(https://github.com/ToucanToco/toucan-data-sdk/pull/98) to be used as a basis for further discussions.

**Comment by adimascio** [comment]
After some discussions, a concern was raised that it would be difficult to express date ranges such ad `D+2 → D+30` where D would itself be a variable (or a symbolic name). Therefore, the following new API is suggested:

```python
def filter_by_date(df, date_col, date_fmt='%Y-%m-%d', start=None, stop=None, atdate=None):
    """
     - `atdate`: keep all rows matching this date exactly,                                                                                                                                   
     - `start`: keep all rows matching this date onwards.                                                                                                                                    
     - `stop`: keep all rows matching dates before this one.                                                                                                                                 
     - `start` and `stop`: keep all rows between `start` and `stop`,                                                                                                                         
    """
```

with support of the following syntax for dates:

- `2018-01-01`
- `(2018-01-01) + 1d` (**with parenthesis**)
- `TODAY`
- `(TODAY) - 2days` (**with parenthesis**)

**Comment by adimascio** [comment]
closed now that https://github.com/ToucanToco/toucan-data-sdk/pull/98 is merged
